name: Actions_for_tests

on:
 push:
  branches: [main]
  tags:
     - '*'
 pull_request:
  branches: [main]

permissions:
  contents: write

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3

  - name: Adding gtest
    run: git clone https://github.com/google/googletest.git third-party/googletest -b release-1.11.0

  - name: Config
    run: cmake -H. -B ${{github.workspace}}/build -DBUILD_TESTS=ON

  - name: Build
    run: cmake --build ${{github.workspace}}/build

  - name: Run tests
    run: build/check

  - name: Build package
    run: cmake --build ${{github.workspace}}/build --target package

  - name: Build source package
    run: cmake --build ${{github.workspace}}/build --target package_source

  - name: CPack
    uses: ncipollo/release-action@v1
    with:
        artifacts: "build/*.deb,build/*.tar.gz,build/*.zip"
        replacesArtifacts: false
        tag: 1.0.5
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true

  - name: Artifacts
    uses: actions/upload-artifact@v4
    with:
        name: example
        path: build/program
